<a href="https://colab.research.google.com/github/Purvsoni/132_PurvSoni/blob/main/Lab5/2_linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
X = torch.from_numpy(inputs)
Y = torch.from_numpy(targets)


$$
\hspace{2.5cm} X \hspace{1.1cm} \times \hspace{1.2cm} W^T \hspace{1.2cm}  + \hspace{1cm} b \hspace{2cm}
$$

$$
\left[ \begin{array}{cc}
73 & 67 & 43 \\
91 & 88 & 64 \\
\vdots & \vdots & \vdots \\
69 & 96 & 70
\end{array} \right]
%
\times
%
\left[ \begin{array}{cc}
w_{11}& w_{21} \\ 
w_{12} & w_{22} \\
w_{13} & w_{23}\\
\end{array} \right]
%
+
%
\left[ \begin{array}{cc}
b_{1} & b_{2}\\
\end{array} \right]
$$

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = torch.utils.data.TensorDataset(X,Y)

In [7]:
# Define data loader
trainloader = torch.utils.data.DataLoader(dataset,batch_size=10)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [9]:
# Define model
model = nn.Linear(X.shape[1],Y.shape[1])
print(model.state_dict())
model.parameters()

OrderedDict([('weight', tensor([[ 0.4984,  0.3557,  0.5598],
        [-0.4223, -0.4953, -0.4096]])), ('bias', tensor([ 0.2977, -0.2929]))])


<generator object Module.parameters at 0x7f504ade92d0>

### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [10]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=1e-4)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [11]:
# Import nn.functional
import torch.nn.functional as F

In [12]:
# Define loss function
loss_fn = F.mse_loss

### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [13]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in trainloader:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(yb,pred)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
        print('Training loss: ', loss_fn(model(X), Y))

In [14]:
# Train the model for 100 epochs
fit(100 , model , loss_fn, optimizer)

Training loss:  tensor(8242.7256, grad_fn=<MseLossBackward>)
Training loss:  tensor(3400.8623, grad_fn=<MseLossBackward>)
Training loss:  tensor(1468.3066, grad_fn=<MseLossBackward>)
Training loss:  tensor(682.9309, grad_fn=<MseLossBackward>)
Training loss:  tensor(353.1192, grad_fn=<MseLossBackward>)
Training loss:  tensor(206.6797, grad_fn=<MseLossBackward>)
Training loss:  tensor(135.9190, grad_fn=<MseLossBackward>)
Training loss:  tensor(97.7909, grad_fn=<MseLossBackward>)
Training loss:  tensor(74.7572, grad_fn=<MseLossBackward>)
Training loss:  tensor(59.4221, grad_fn=<MseLossBackward>)
Training loss:  tensor(48.4816, grad_fn=<MseLossBackward>)
Training loss:  tensor(40.3270, grad_fn=<MseLossBackward>)
Training loss:  tensor(34.0859, grad_fn=<MseLossBackward>)
Training loss:  tensor(29.2300, grad_fn=<MseLossBackward>)
Training loss:  tensor(25.4081, grad_fn=<MseLossBackward>)
Training loss:  tensor(22.3722, grad_fn=<MseLossBackward>)
Training loss:  tensor(19.9394, grad_fn=<MseLo

In [15]:
# Generate predictions
preds = model(X)
preds

tensor([[ 57.2305,  70.3501],
        [ 82.0365,  99.9552],
        [118.9766, 134.5175],
        [ 21.1571,  37.4559],
        [101.6371, 117.5808],
        [ 57.2305,  70.3501],
        [ 82.0365,  99.9552],
        [118.9766, 134.5175],
        [ 21.1571,  37.4559],
        [101.6371, 117.5808],
        [ 57.2305,  70.3501],
        [ 82.0365,  99.9552],
        [118.9766, 134.5175],
        [ 21.1571,  37.4559],
        [101.6371, 117.5808]], grad_fn=<AddmmBackward>)

In [16]:
# Compare with targets
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

Now we can define the model, optimizer and loss function exactly as before.

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

# Ex 1

In [17]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()

In [18]:
from sklearn.model_selection import train_test_split

X_Train,X_Test,Y_Train,Y_Test = train_test_split(inputs,targets,test_size=0.2,random_state=132)

In [19]:
model1.fit(X_Train,Y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
Y_pred = model1.predict(X_Test)

In [21]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_Test,Y_pred))
Y_pred,Y_Test

0.45185506


(array([[118.66335 , 133.02362 ],
        [ 57.141125,  69.92001 ],
        [ 20.867579,  37.07937 ]], dtype=float32), array([[119., 133.],
        [ 56.,  70.],
        [ 22.,  37.]], dtype=float32))