<a href="https://colab.research.google.com/github/Purvsoni/132_PurvSoni/blob/main/Lab6/Lab06_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ML/Lab6/BuyComputer.csv')

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [5]:

#Declare label as last column in the source file
Y = data.iloc[:,-1]

In [6]:
#Declaring X as all columns excluding last
X = data.iloc[:,:2]

In [7]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,random_state=132,test_size=0.5)

In [8]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)
entries = len(X_train[:,0])
entries

2


200

In [10]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [11]:
# Sigmoid function
def sigmoid(z):
  sig = 1/(1+np.exp(-z))
  return sig

In [12]:
def predict(inputs):
    return np.matmul(inputs,w)+b
def h(inputs):
    return sigmoid(predict(inputs))

In [13]:
#Loss function
def loss_func(y,a):
    J = 0
    for i in range(0,len(y)):
        J += y[i]*np.log(h(X_train[i]))+(1-y[i])*np.log(1-h(X_train[i]))
    return -J
def gradient_descend(lr):
    tmp = h(X_train)
    for i in range(0,len_x):
        w[i]-=lr*np.sum((tmp.flatten()-y_train)*X_train[:,i])
    global b
    b-=lr*np.sum(tmp.flatten()-y_train)       

In [14]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

In [15]:
#Repeating the process 3000 times
for i in range(0,3000):
    gradient_descend(lr=alpha)

In [16]:
#Print weight
w

[3.3059023334669284, 1.1287326903623676]

In [17]:
#print bias
b

-0.6185713083431732

In [18]:
#predicting the label
y_ = h(X_test)
y_ = y_.flatten()
y_predicted = (y_ >= .5).astype(int)
y_predicted

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1])

In [19]:
#print actual and predicted values in a table
y_test

150    0
73     0
121    0
79     0
207    0
      ..
124    0
258    1
296    1
393    1
397    1
Name: Purchased, Length: 200, dtype: int64

In [20]:
# Calculating accuracy of prediction
np.sum(y_predicted == y_test)/len(X_test)

0.81

In [21]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predicted)

array([[108,  27],
       [ 11,  54]])

In [22]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_predicted = LR.predict(X_test)

In [23]:
confusion_matrix(y_test, y_predicted)

array([[119,  16],
       [ 14,  51]])